### PR TITLE
Add note class

### PR DESCRIPTION
**Pull request by kerrermanisNL**
Able to use list, detail, create and delete for notes. Update doesn't quite work, because it's complaining about pinning notes to deals (even though none is specified). Don't have a fix for now.

Waits for #1

### CODE REVIEW

**Comment by carlos-loggi** [comment]
Suppose you don't associate the Note to a Deal, but you associate it with a Person or an Organization. Even in those cases it won't update? A Note must always be linked to one of those objects.

**Comment by kerrermanisNL** [comment]
@carlos-loggi In my case I have an existing `Note` that is associated with an `Organization`. When I try to update the note via:

```
api = PipedriveAPI('key')
n = api.note.detail(123)
n.content = "Updated!"
api.note.update(n)
```
I get the following error: `pipedrive.base.PipedriveException: Note can only be pinned to deal if it is associated with the deal.`. Which is weird since I'm not doing any pinning, or anything with a `Deal` for that matter. I am able to update it manually via the Pipedrive web interface.
``

**Comment by carlos-loggi** [comment]
Inspect the Note that is returned by `api.note.detail(123)`, and also what this Note's `to_primitive` returns.

If in both cases there's nothing wrong with the data in your Node, then there's a good chance that the Pipedrive API has a bug. We found a lot of bugs and erratic behaviors from the API when working with it, and this was one of the many reasons why we stopped using Pipedrive.

If there seems to be a bug in the API, try reproducing it in their playground: https://developers.pipedrive.com/v1#methods-Notes

**Comment by kerrermanisNL** [comment]
@carlos-loggi Thanks for sticking with me ;) after some digging I think it has to do with the `to_primitive()` method, or the way the Pipedrive API handles these values. The `to_primitive` values seem to be alright, but I'm not sure what it's supposed to be returning. It returns Python objects such as `False` and `True` for the `BooleanType` fields. This might actually be wrong, or the way the Pipedrive API interprets this is wrong. For now I've removed to `is_pinned_to_..._flag` attributes from the `Note` model. These aren't really important (for me anyway), and they don't seem to be doing a whole lot (haven't found out what it is that they do). This makes the `update()` method work like it should.

**Comment by kerrermanisNL** [comment]
Moved to #4

**Pull request closed without merging**
